apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  template:
    spec:
      containers:
        - name: my-nginx
          envFrom:
            - configMapRef:
                name: envs
            - configMapRef:
                name: shared-envs
