resources:
  - deployment.yaml
  - service.yaml

# configMapGenerator
# generate a ConfigMap named envs-<some-hash> where each key/value pair in the
# env file appears as a data entry (separated by \n).
configMapGenerator:
  - envs:
      - shared-env.yaml
    name: shared-envs
